apiVersion: v1
kind: Service
metadata:
  labels:
    app: mc-lb
  name: mc-lb
spec:
  type: LoadBalancer
  externalTrafficPolicy: Cluster
  ports:
  - name: mc-lb-port
    port: 25565
    protocol: TCP
    targetPort: minecraft
  selector:
    app: mc-backend
  sessionAffinity: None
